name: teste_create_flutter

description: sua_descrição

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ou sua versão

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  # ... suas outras dependências

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0  # <-- Corrigido! Agora está no nível correto.

dependency_overrides:  # <--- SEÇÃO dependency_overrides
  # async: ^2.13.0  # <-- Se precisar sobrepor dependências, adicione aqui.

flutter:
  uses-material-design: true
